<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwXGfkPcEAClGivrF/n45'."\n".'lHy5d6o4rpQ7d+gNczK9ibvxyhjz912PlIPVRkz3ejXRaT6lor5qDYcRSMxz9lQn'."\n".'SuDqldjO8tvNYL8g9uT1cbpzAG2NcsXWoNMJdHc5Q5lV4NODQU7UAjTaF9IoQxyj'."\n".'y3AXY5ivQlw7I0BpEIAltYDY1phYVHPfMtmF+SDED9nprecaYTnQuVePhOa04Sfd'."\n".'/t8nE2RgvP85QLvcBp6lmMNwVc3mV/QUuK5jPnPh8n/nWzcfxLnoX+dqlGhDEixY'."\n".'6upOAgihP3OSIpPpVBly1TteXwPCuRHBee9g8WnIlUahQnKFBI14LNmfY6as0Gby'."\n".'fQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
