<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnsqlQW\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnsqlQW/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZnsqlQW.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZnsqlQW\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerZnsqlQW\appAppKernelDevDebugContainer([
    'container.build_hash' => 'ZnsqlQW',
    'container.build_id' => 'ea0e09cf',
    'container.build_time' => 1717950103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnsqlQW');
